### PR TITLE
Fixed mistake, header only version of Catch2 is in single_include folder

### LINKED ISSUE #2: Linking Errors due to not Compiling include/internal/*.cpp Files
When attempting to use this meson patch for Catch you will encounter link errors as a result of the implementation code contained in `include/internal/*.cpp` files not being compiled or baked into the `catch_dep` dependency in any way. I was able to reproduce this problem under a very simple test project under both windows-msys2/g++ and debian/g++.

A few Catch issues that discuss this problem:
 * https://github.com/catchorg/Catch2/issues/1097
 * https://github.com/catchorg/Catch2/issues/1085
 * https://github.com/catchorg/Catch2/issues/1142

It appears there are two recommended solutions by the developers. The first is to use the `single_include` directory instead of `include` that bundles *all* of the catch code into a single monolithic file; this is a one line fix. This unfortunately increases build times due to having to compile all of catch every time the monolithic `catch.hpp` is included. 
The second would be to compile the .cpp files present in `include/internal` in our `build.meson`, with the obvious downside being that it would increase maintenance effort due to making the meson build process more complex (e.g. having to support multiple OSs and compilers etc.) as well as making the build.meson reliant on the internal file structure of Catch. The upside being that it would reduce repeated compilation and therefore build times.

Do the maintainers/other contributors have any thoughts as to what direction to take?

### PR DESCRIPTION
**Pull request by jeandet**
Closes #2, maybe later we could add an option to chose between header only and normal version.

### CODE REVIEW

**Comment by sarum9in** [comment]
@jeandet You could just add another `declare_dependency()` for this.

**Comment by jeandet** [comment]
@sarum9in, I wonder what is the best between project options or having another dependency with another name like we did with GTest. It breaks in somehow the naming convention.
Maybe we should make a choice and propose a convention for Wraps with such options.

**Comment by sarum9in** [comment]
I honestly don't understand what's so wrong having multiple `*_dep` variables inside one wrap. That's the way `meson` language is supposed to work, why do we need to introduce something artificial?

https://github.com/mesonbuild/gtest/blob/1.8.0/googletest/meson.build looks totally reasonable to me.

**Comment by jeandet** [comment]
@sarum9in, me too, my point is more, what is the pattern? The wrap documentation is not the best, how can we make this easy for users? Can we set a naming convention? Should we update the readme and say "this is the documentation, for each wrap look it's readme"? 

The \<name\>_dep is good since users doesn't need to read the doc to guess it.

**Comment by sarum9in** [comment]
Do you refer to strict `${project}_dep`? What I am talking about `${project}_dep` and optional `${project}_${variant}_dep`. And I believe users of meson are developers and should be able to just open `meson.build` and take a look what they are using.

**Pull request merged**
